#!/bin/bash
# ---------------------------------------------------------------------------
# One-shot cluster initializer for the docker-compose stack (IMPROVEMENT_PLAN §0.4).
#
# Replaces the manual chain of config_servers.sh + create_shards.sh +
# connect_shards.sh + the hand-created Compass indices (SETUP.md). Runs inside a
# mongo:4.4 container on the compose network, reaching every node by service name.
#
# It is intentionally IDEMPOTENT: re-running against an already-initialized
# cluster logs "already initialized" and moves on, so `docker compose up` after a
# restart is safe.
# ---------------------------------------------------------------------------
set -u

# Wait until a mongod/mongos answers ping (it does so even before rs.initiate).
wait_reachable() {
  local host=$1
  echo "→ waiting for $host to accept connections..."
  until mongo --quiet --host "$host" --eval "db.adminCommand('ping').ok" 2>/dev/null | grep -q 1; do
    sleep 2
  done
  echo "  $host is reachable."
}

# Wait until the node reports itself PRIMARY (replica set has elected a leader).
wait_primary() {
  local host=$1
  echo "→ waiting for a primary on $host..."
  until mongo --quiet --host "$host" --eval "rs.isMaster().ismaster" 2>/dev/null | grep -q true; do
    sleep 2
  done
  echo "  $host is primary."
}

# --- 1. Config-server replica set -----------------------------------------
wait_reachable config-svr-1:27017
echo "→ initiating config-server replica set..."
mongo --quiet --host config-svr-1:27017 --eval '
rs.initiate({
  _id: "config-svr-replica-set",
  configsvr: true,
  members: [
    { _id: 0, host: "config-svr-1:27017" },
    { _id: 1, host: "config-svr-2:27017" },
    { _id: 2, host: "config-svr-3:27017" }
  ]
});' || echo "  config RS already initialized."
wait_primary config-svr-1:27017

# --- 2. Shard replica sets -------------------------------------------------
for s in 1 2 3; do
  wait_reachable "shard-${s}-node-a:27017"
  echo "→ initiating shard-${s} replica set..."
  mongo --quiet --host "shard-${s}-node-a:27017" --eval "
rs.initiate({
  _id: 'shard-${s}-replica-set',
  members: [
    { _id: 0, host: 'shard-${s}-node-a:27017' },
    { _id: 1, host: 'shard-${s}-node-b:27017' },
    { _id: 2, host: 'shard-${s}-node-c:27017' }
  ]
});" || echo "  shard-${s} RS already initialized."
  wait_primary "shard-${s}-node-a:27017"
done

# --- 3. Routers: add shards, enable + shard collections, create indices ----
# Routers (mongos) only become reachable once the config RS above has a primary.
wait_reachable router-1:27017

echo "→ wiring shards + sharding the 'bank' collections + creating indices..."
mongo --quiet --host router-1:27017 <<'EOF'
sh.addShard("shard-1-replica-set/shard-1-node-a:27017");
sh.addShard("shard-2-replica-set/shard-2-node-a:27017");
sh.addShard("shard-3-replica-set/shard-3-node-a:27017");

sh.enableSharding("bank");

var bank = db.getSiblingDB("bank");
bank.createCollection("users");
bank.createCollection("transactions");

// Hashed shard keys → even distribution across shards (the project's thesis).
sh.shardCollection("bank.users", { user_id: "hashed" });
sh.shardCollection("bank.transactions", { _id: "hashed" });

// Indices that SETUP.md previously asked you to create by hand in Compass.
bank.transactions.createIndex({ sender_id: 1 });
bank.transactions.createIndex({ receiver_id: 1 });
bank.users.createIndex({ user_id: 1 });

sh.setBalancerState(true);
print("cluster wiring complete; shard status:");
sh.status();
EOF

# --- 4. Seed data (IMPROVEMENT_PLAN §0.5) ----------------------------------
# Deterministically generated by scripts/seed/generate.js and mounted into this
# container at /seed (see docker-compose.yml's SEED_DIR build arg / volume).
# Idempotent: skips the import if the collection already has documents, so a
# restart against existing data doesn't reseed or duplicate rows.
seed_collection() {
  local collection=$1
  local file=$2
  local count
  count=$(mongo --quiet --host router-1:27017 bank --eval "db.${collection}.countDocuments({})" 2>/dev/null)
  if [ "$count" != "0" ]; then
    echo "  bank.${collection} already has ${count} documents; skipping seed import."
    return
  fi
  echo "→ importing ${file} into bank.${collection}..."
  mongoimport --host router-1:27017 --db bank --collection "${collection}" --file "${file}" --jsonArray
}

seed_collection users "/seed/users.json"
seed_collection transactions "/seed/transactions.json"

echo "✓ Cluster initialization complete."
